<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SOAP Note – {{ $consultation->patient_name }}</title>
    <style>
        @page { margin: 32px 36px; }
        body { font-family: DejaVu Sans, sans-serif; color: #334155; font-size: 11.5pt; line-height: 1.55; }
        .header { border-bottom: 2px solid #4f46e5; padding-bottom: 12px; margin-bottom: 20px; }
        .brand { color: #4f46e5; font-weight: bold; font-size: 13pt; letter-spacing: 0.5px; }
        h1 { color: #0f172a; font-size: 18pt; margin: 6px 0 2px; }
        .meta { color: #64748b; font-size: 10pt; }
        .section { margin-top: 18px; page-break-inside: avoid; }
        .section-title { background: #eef2ff; color: #4338ca; padding: 6px 10px; border-radius: 4px; font-weight: bold; font-size: 11pt; }
        .field { margin: 8px 0; }
        .field-label { font-size: 9.5pt; text-transform: uppercase; letter-spacing: 0.6px; color: #64748b; font-weight: 600; }
        .field-value { color: #1e293b; margin-top: 2px; }
        ul { margin: 4px 0 0 18px; padding: 0; }
        .footer { margin-top: 28px; padding-top: 10px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 9pt; text-align: center; }
    </style>
</head>
<body>

@php
    $renderField = function ($label, $value) {
        $out = '<div class="field"><div class="field-label">' . e($label) . '</div><div class="field-value">';
        if (is_array($value)) {
            if (empty($value)) {
                $out .= '<em style="color:#94a3b8">None.</em>';
            } else {
                $out .= '<ul>';
                foreach ($value as $item) $out .= '<li>' . e($item) . '</li>';
                $out .= '</ul>';
            }
        } else {
            $out .= nl2br(e($value ?: 'Not documented.'));
        }
        return $out . '</div></div>';
    };
@endphp

<div class="header">
    <div class="brand">SMART SCRIBE</div>
    <h1>{{ $consultation->patient_name }}</h1>
    <div class="meta">SOAP Note · Generated {{ $consultation->updated_at->format('M j, Y · g:i A') }}</div>
</div>

<div class="section">
    <div class="section-title">S — Subjective</div>
    {!! $renderField('Chief Complaint', $soap['subjective']['chief_complaint'] ?? null) !!}
    {!! $renderField('History of Present Illness', $soap['subjective']['history_of_present_illness'] ?? null) !!}
    {!! $renderField('Review of Systems', $soap['subjective']['review_of_systems'] ?? null) !!}
</div>

<div class="section">
    <div class="section-title">O — Objective</div>
    {!! $renderField('Vitals', $soap['objective']['vitals'] ?? null) !!}
    {!! $renderField('Physical Exam', $soap['objective']['physical_exam'] ?? null) !!}
    {!! $renderField('Diagnostics', $soap['objective']['diagnostics'] ?? null) !!}
</div>

<div class="section">
    <div class="section-title">A — Assessment</div>
    {!! $renderField('Primary Diagnosis', $soap['assessment']['primary_diagnosis'] ?? null) !!}
    {!! $renderField('Differential Diagnoses', $soap['assessment']['differential_diagnoses'] ?? []) !!}
    {!! $renderField('Clinical Reasoning', $soap['assessment']['clinical_reasoning'] ?? null) !!}
</div>

<div class="section">
    <div class="section-title">P — Plan</div>
    {!! $renderField('Medications', $soap['plan']['medications'] ?? []) !!}
    {!! $renderField('Investigations', $soap['plan']['investigations'] ?? []) !!}
    {!! $renderField('Follow-up', $soap['plan']['follow_up'] ?? null) !!}
    {!! $renderField('Patient Education', $soap['plan']['patient_education'] ?? null) !!}
</div>

<div class="footer">
    Generated by Smart Scribe · AI-assisted documentation must be reviewed and signed by the attending physician.
</div>

</body>
</html>
